name: C/C++ AppImage

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build-appimage:
    #runs-on: self-hosted
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout fmedia
        uses: actions/checkout@v3
        with:
          # repository: statz/fmedia
          path: fmedia

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl build-essential g++  cmake patch dos2unix  make pkg-config \
          gcc-multilib g++-multilib \
          gcc alsa-source  libghc-alsa-core-dev libpulse-dev  libjack-dev	libglib2.0-dev libdbus-1-dev libffi-dev  \
          pipewire libpipewire-0.3-dev gstreamer1.0-pipewire libpipewire-0.3-modules pipewire-audio-client-libraries libpipewire-0.3-0  \
          libwxgtk3.0-gtk3-dev  libcanberra-gtk3-dev libghc-gtk3-dev  libgtk-3-dev \
          dbus-c++ #TODO: cleanup unused
          #- run: ls -l /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h
      - run: pkg-config --cflags dbus-1
      - name: Add repos
        run: |
          git clone https://github.com/stsaz/ffbase
          git clone https://github.com/stsaz/ffaudio
          git clone https://github.com/stsaz/ffos
          git clone https://github.com/stsaz/avpack
      - name: prebuild alib3
        working-directory: fmedia/alib3
        run: make
      - name: preinstall alib3
        working-directory: fmedia/alib3
        run: make install
      - name: build fmedia
        working-directory: fmedia
        run: make
      - name: install fmedia
        working-directory: fmedia
        run: make install
      - run: mv fmedia/fmedia-1 .
      - run: mv fmedia/AppImageBuilder.yml .
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        # uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|fmedia|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
          
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
      - uses: actions/upload-artifact@v2
        with:
          name: fmedia
          path: './fmedia-1'
      - run: ls -l



